version: '3.4'

services:
  zipkin-server:
    container_name: openzipkin
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - ms-network

  cambio-db:
    container_name: cambio-db
    image: mysql:5.7.22
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - ms-network

  naming-server:
    container_name: naming-server
    image: doug397/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - ms-network

  api-gateway:
    container_name: api-gateway
    image: doug397/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      SPRING.ZIPKIN.BASE-URL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge