server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cambio
          uri: lb://cambio-service
          predicates:
          - Path=/cambio/**
        - id: book
          uri: lb://book-service
          predicates:
          - Path=/book/**
        - id: open-api
          uri: lb://api-gateway
          predicates:
          - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
