server:
  port: 8100
  forward-headers-strategy: framework
spring:
  application:
    name: book-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail_on_empty_beans: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    #schemas: book_service
    user: root
    password: root

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 2
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true

springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    #disable-swagger-default-url: true
    config-url: /book-service/v3/api-docs/swagger-config
    url: /book-service/v3/api-docs
    path: /book-service/v3/api-docs





